// session, login, logout
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_FORM_CHANGE = 'LOGIN_FORM_CHANGE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// store
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const FIND_REQUEST = 'FIND_REQUEST';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const CREATE_ERROR = 'CREATE_ERROR';
export const FIND_ERROR = 'FIND_ERROR';
export const FETCH_ERROR = 'FETCH_ERROR';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const DELETE_ERROR = 'DELETE_ERROR';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const FIND_SUCCESS = 'FIND_SUCCESS';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const SYNC_STORE = 'SYNC_STORE';

// download
export const DOWNLOAD = 'DOWNLOAD';

// form
export const INITIALIZE_FORM = 'INITIALIZE_FORM';
export const REVERT_FORM = 'REVERT_FORM';
export const CHANGE_FORM = 'CHANGE_FORM';
export const SUBMIT_FORM_REQUEST = 'SUBMIT_FORM_REQUEST';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_ERROR = 'SUBMIT_FORM_ERROR';

// form submissions
export const SUBMIT_BRAND_SETTINGS_FORM = 'SUBMIT_BRAND_SETTINGS_FORM';
export const SUBMIT_COMPANY_SETTINGS_FORM = 'SUBMIT_COMPANY_SETTINGS_FORM';
